#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : md4c
Version  : 0.4.8
Release  : 3
URL      : https://github.com/mity/md4c/archive/release-0.4.8/md4c-0.4.8.tar.gz
Source0  : https://github.com/mity/md4c/archive/release-0.4.8/md4c-0.4.8.tar.gz
Summary  : Markdown parser library with a SAX-like callback-based interface.
Group    : Development/Tools
License  : BSD-3-Clause MIT
Requires: md4c-bin = %{version}-%{release}
Requires: md4c-lib = %{version}-%{release}
Requires: md4c-license = %{version}-%{release}
Requires: md4c-man = %{version}-%{release}
BuildRequires : buildreq-cmake

%description
[![Linux Build Status (travis-ci.com)](https://img.shields.io/travis/mity/md4c/master.svg?logo=linux&label=linux%20build)](https://travis-ci.com/mity/md4c)
[![Windows Build Status (appveyor.com)](https://img.shields.io/appveyor/ci/mity/md4c/master.svg?logo=windows&label=windows%20build)](https://ci.appveyor.com/project/mity/md4c/branch/master)
[![Code Coverage Status (codecov.io)](https://img.shields.io/codecov/c/github/mity/md4c/master.svg?logo=codecov&label=code%20coverage)](https://codecov.io/github/mity/md4c)
[![Coverity Scan Status](https://img.shields.io/coverity/scan/mity-md4c.svg?label=coverity%20scan)](https://scan.coverity.com/projects/mity-md4c)

%package bin
Summary: bin components for the md4c package.
Group: Binaries
Requires: md4c-license = %{version}-%{release}

%description bin
bin components for the md4c package.


%package dev
Summary: dev components for the md4c package.
Group: Development
Requires: md4c-lib = %{version}-%{release}
Requires: md4c-bin = %{version}-%{release}
Provides: md4c-devel = %{version}-%{release}
Requires: md4c = %{version}-%{release}

%description dev
dev components for the md4c package.


%package lib
Summary: lib components for the md4c package.
Group: Libraries
Requires: md4c-license = %{version}-%{release}

%description lib
lib components for the md4c package.


%package license
Summary: license components for the md4c package.
Group: Default

%description license
license components for the md4c package.


%package man
Summary: man components for the md4c package.
Group: Default

%description man
man components for the md4c package.


%prep
%setup -q -n md4c-release-0.4.8
cd %{_builddir}/md4c-release-0.4.8

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1620754816
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1620754816
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/md4c
cp %{_builddir}/md4c-release-0.4.8/LICENSE.md %{buildroot}/usr/share/package-licenses/md4c/aba96670ff8909af4d895e6e8cfcfa3c42ec43d7
cp %{_builddir}/md4c-release-0.4.8/test/LICENSE %{buildroot}/usr/share/package-licenses/md4c/76cf8e32adfd0d4706a0408a206265bbde15350b
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/md2html

%files dev
%defattr(-,root,root,-)
/usr/include/md4c-html.h
/usr/include/md4c.h
/usr/lib64/cmake/md4c/md4cConfig-relwithdebinfo.cmake
/usr/lib64/cmake/md4c/md4cConfig.cmake
/usr/lib64/libmd4c-html.so
/usr/lib64/libmd4c.so
/usr/lib64/pkgconfig/md4c-html.pc
/usr/lib64/pkgconfig/md4c.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libmd4c-html.so.0
/usr/lib64/libmd4c-html.so.0.4.8
/usr/lib64/libmd4c.so.0
/usr/lib64/libmd4c.so.0.4.8

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/md4c/76cf8e32adfd0d4706a0408a206265bbde15350b
/usr/share/package-licenses/md4c/aba96670ff8909af4d895e6e8cfcfa3c42ec43d7

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/md2html.1
